all: pip-install

run: play.py
	./play.py

pip-install:
	python3 -m pip install -U pip
	python3 -m pip install -U distro-info
	python3 -m pip install -U python-debian
	python3 -m pip install -U gymnasium
	python3 -m pip install -U pettingzoo